version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "chore:"
  - package-ecosystem: "gomod"
    directory: "contrib/morty-cli-docs"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "chore:"
