version: 2
updates:
  # Disable for now as pnpm isn't supported yet
  # See: https://github.com/dependabot/dependabot-core/issues/1736#issuecomment-1489987159
  # - package-ecosystem: "npm"
  #   directory: "/"
  #   schedule:
  #     interval: "weekly"
  #   commit-message:
  #     prefix: "chore:"
  - package-ecosystem: "gomod"
    directory: "contrib/morty-cli-docs"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "chore:"
