name: PR

on:
  workflow_dispatch:
  pull_request:
    branches: [main]

jobs:
  build:
    name: Build documentation
    runs-on: ubuntu-22.04
    steps:
      - id: go-cache-paths
        run: echo "GOMODCACHE=$(go env GOMODCACHE)" >> $GITHUB_ENV
      
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Go cache 
        uses: actions/cache@v3
        with:
          path: ${{ env.GOMODCACHE }}
          key: ${{ runner.os }}-go-mod-${{ hashFiles('**/go.sum') }}
      
      - name: PNPM cache 
        uses: actions/cache@v3
        with:
          key: ${{ runner.os }}-next-${{ hashFiles('**/pnpm-lock.yaml') }}-${{ hashFiles('**.[jt]s', '**.[jt]sx', '**.md', '**.mdx') }}
          restore-keys: ${{ runner.os }}-next-${{ hashFiles('**/pnpm-lock.yaml') }}-
          path: |
            .next/cache
            node_modules

      - uses: actions/setup-go@v4
        with:
          go-version: 1.19

      - uses: pnpm/action-setup@v2
        with:
          version: 7

      - name: Install Node.js dependencies
        run: pnpm install
      
      - name: Install Go dependencies
        run: cd contrib/morty-cli-docs && go mod download

      - name: Generate documentation for Morty CLI
        run: cd contrib/morty-cli-docs && go run main.go
  
      - name: Build Morty documentation
        run: pnpm build
